name: Tests

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r src/v2/requirements-dev.txt

      - name: Run tests
        working-directory: src/v2
        run: pytest
